import type { Props } from "../components/ExperienceCard.astro";

export const experiences: Props[] = [
  {
    id: 0,
    title: "INTERNSHIP",
    time: "May 2025 - August 2025",
    company: "Meta",
    logo: "/companies/meta_logo.jpeg",
    jobTitle: "Software Engineer Intern",
    description: undefined,
    bullets: [
      "Implemented both the back-end and front-end of an Ads unit for Instagram feed using Hack and Python, which can potentially reach 5M users daily, aiming to drive up revenue.",
      "Ran multiple A/B experiments and wrote SQL queries to analyze data provided by over 1M daily reached users, including exposure, revenue, CTR, etc.",
      "Extended logging functions for all Ads units in Instagram Reels, providing more analytical logging data without taking up too much database storage.",
      "Migrated the front-end of several Facebook Ads units to a new internal framework, harnessing more compatibility and consistency without any change in user experience",
    ],
    techStack: ["PHP (Hack)", "Python", "Instagram", "Facebook", "Mobile", "Front-End", "Back-End", "Cross-Platform", "A/B Testing", "User Expierience"]
  },
  {
    id: 1,
    title: "INTERNSHIP",
    time: "July 2023 - April 2024",
    company: "Amazon Web Services",
    logo: "/companies/amazon_web_services_logo.jpeg",
    jobTitle: "Applied Scientist Intern",
    description: undefined,
    bullets: [
      "Contributed to the widely used Deep Graph Library (DGL)(12.5k stars repo), making over 30 pull requests on GitHub.",
      "Revamped sampling processes through pre-allocated memory and multi-threading, achieving a 35x speed improvement.",
      "Developed a custom random distribution function to replace a standard one, improving efficiency by 15x.",
      "Designed and implemented a new feature for distributed multi-GPU data loading, enhancing scalability and performance.",
      "Conducted benchmark testing and profiling for distributed multi-GPU training, providing key recommendations for improvement.",
      "Resolved complex bugs and performance issues in mostly C++ and Python, utilizing PyTorch, TorchScript, and multi-processing.",
    ],
    techStack: ["C++", "Python", "Open Source", "Machine Learning", "PyTorch", "Multi-threading", "CPU", "GPU", "Optimization", "Profiling", "Graph Neural Networks"],
    link: "https://github.com/dmlc/dgl",
  },
  {
    id: 2,
    title: "RESEARCH",
    time: "January 2024 - June 2024",
    company: "Scalable Representation Learning on Large Dynamic Graphs",
    description: "Proposed a new scalable spatio-temporal graph network model EGSN which adopts a relatively less explored model evolution method and incorporates the inspiring message-passing, sampling and aggregation mechanisms from static graph methods. It's also combined with an RNN structure to adjust weights over time. The experiment results showed some significant improvements comparing to the baseline methods in some situations.",
    techStack: ["Python", "Machine Learning", "PyTorch", "Temporal GNN", "RNN", "Benchmark"],
    // link: "https://github.com/dmlc/dgl",
    rowSpan: "md:row-span-4"
  },
  {
    id: 3,
    title: "PROJECT",
    time: "Feburary 2025 - March 2025",
    company: "Simple Path Tracer",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: undefined,
    bullets: [
      "Implemented a simple GUI for ray tracing and path tracing renderer using C++.", 
      "Including features like physically based rendering, nested dielectrics, reflection and refraction, area lights, multiple importance sampling, BVH acceleration, sky box, de-noising, anti-aliasing, etc.",
    ],
    techStack: ["C++", "Parallel Computation", "Ray Tracing", "Path Tracing", "Rendering"],
    // link: "https://github.com/dmlc/dgl",
    image: "/images/pathtracer.png",
    rowSpan: "md:row-span-8"
  },
  {
    id: 3,
    title: "PROJECT",
    time: "July 2022 - December 2022",
    company: "Haopenyou (好盆友)",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    jobTitle: "Mobile Engineer",
    description: undefined,
    bullets: [
      "Implemented the front-end of a cross-platform mobile app for women’s pelvic health using React Native.",
      "Optimized performance by 30% through JavaScript page caching mechanisms.",
      "Built a comprehensive survey system with support for custom logic-based, multiple-choice, and scale-based questions, while enabling efficient data collection through a backend interface.",
      "Designed a set of RESTful API and drafted the documents.",
    ],
    techStack: ["Mobile Engineering", "JavaScript", "React.js", "React Native", "RESTful API", "Node.js", "Figma"],
    // link: "https://github.com/dmlc/dgl",
    rowSpan: "md:row-span-4"
  },
  {
    id: 4,
    title: "PROJECT",
    time: "November 2022 - December 2022",
    company: "Smart Home Management System",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: "Built a webpage managing Smart Home devices, with React.js & Typescript in front-end and Gin & Gorm in back-end.",
    bullets: [],
    techStack: ["Full Stack", "TypeScript", "React.js", "Golang", "Gin", "Gorm", "MySQL", "Docker", "RESTful API"],
    // link: "https://github.com/RamonZhou/Mini-HTTP-Server",
    rowSpan: "md:row-span-3"
  },
  {
    id: 5,
    title: "PROJECT",
    time: "March 2022 - June 2022",
    company: "MiniSQL",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: "Developed a database management system in C++ supporting insertion, deletion, update, and selection operations, achieving a 99% reduction in selection time through B+-tree indexing.",
    bullets: [],
    techStack: ["C++", "MySQL", "Data Structure", "Memory Management"],
    link: "https://github.com/RamonZhou/MiniSQL",
    rowSpan: "md:row-span-3"
  },
  {
    id: 6,
    title: "PROJECT",
    time: "October 2022 - December 2022",
    company: "Mini Linux Kernel",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: "Created a simplified Linux kernel for RISC-V64, supporting key OS functionalities such as virtual memory, interrupts, task scheduling, and user mode operations.",
    bullets: [],
    techStack: ["RISC-V", "C", "QEMU", "Operating Systems", "Virtual Memory", "Docker", "Assembly"],
    // link: "https://github.com/RamonZhou/MiniSQL",
    rowSpan: "md:row-span-3"
  },
  {
    id: 7,
    title: "PROJECT",
    time: "November 2022",
    company: "Simple HTTP Server",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: "Built a C++ HTTP server capable of handling concurrent GET/POST requests, using Linux sockets, multithreading, and a custom thread pool, improving server performance under high concurrency.",
    bullets: [],
    techStack: ["C++", "Thread Pool", "HTTP", "Computer Networks", "Multi-threading", "Conditional Variables"],
    link: "https://github.com/RamonZhou/Mini-HTTP-Server",
    rowSpan: "md:row-span-3"
  },
  {
    id: 8,
    title: "PROJECT",
    time: "April 2022 - June 2022",
    company: "Chessboard Game",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    // jobTitle: "Mobile Engineer",
    description: "Designed a first-person perspective chessboard game in C++ on Windows using OpenGL (GLFW & GLAD), implementing camera transformations, Phong shading, skybox rendering, parameter editing and depth peeling.",
    bullets: [],
    techStack: ["C++", "OpenGL", "GLFW", "GLAD", "Computer Graphics", "IMGUI"],
    // link: "https://github.com/RamonZhou/Mini-HTTP-Server",
    rowSpan: "md:row-span-3"
  },
  {
    id: 9,
    title: "PROJECT",
    time: "January 2023",
    company: "ROOTTOOR",
    // logo: "/companies/amazon_web_services_logo.jpeg",
    jobTitle: "Global Game Jam 2023",
    description: "Developed a 2D game with Unity3D engine, contributing to the game UI and the entire inventory system, utilizing Sprites and Tilemap tool. Also Implemented character animations and event triggers with C#.",
    bullets: [],
    techStack: ["Game Development", "Unity3D", "C#", "UI", "Animation"],
    link: "https://v3.globalgamejam.org/2023/games/root-tower-2",
    rowSpan: "md:row-span-3"
  },
]